---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: appservers
  remote_user: root
  become: yes
  become_method: sudo
  vars_files:
  - group_vars/main.yml

  roles:
#    - selinux
    - jdk
    - tomcat
    - deploywar
